var colleges = `[
	{ 
		"collegeID": "1",
		"collegeName": "Savannah State University",
		"collegeType": "Public",
		"profileImage": "https://www.savannahstate.edu/places/images/hill-hall.jpg",
		"collegeURL": "http://www.savannahstate.edu/",
		"locationCity": "Savannah",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "29%",
		"tuitionInState": "$9,493",
		"tuitionOutOfState": "$19,954",
		"exclude": "false"
	},
	{ 
		"collegeID": "2",
		"collegeName": "University of Georgia",
		"collegeType": "Public",
		"profileImage": "https://www.engineering.uga.edu/uploads/main/engr_coverdell.jpg",
		"collegeURL": "http://www.uga.edu/",
		"locationCity": "Athens",
		"locationState": "GA",
		"baselineACT": "30",
		"baselineGPA": "3.86",
		"baselineAPCount": "8",
		"acceptanceRate": "49%",
		"tuitionInState": "$17,412",
		"tuitionOutOfState": "$37,098",
		"exclude": "false"
	},
	{ 
		"collegeID": "3",
		"collegeName": "Georgia Institute of Technology",
		"collegeType": "Public",
		"profileImage": "https://www.gatech.edu/sites/default/files/uploads/images/superblock_images/tower.png",
		"collegeURL": "http://www.gatech.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "32",
		"baselineGPA": "3.86",
		"baselineAPCount": "8",
		"acceptanceRate": "22%",
		"tuitionInState": "$17,340",
		"tuitionOutOfState": "$38,452",
		"exclude": "false"
	},
	{ 
		"collegeID": "4",
		"collegeName": "Clayton State University",
		"collegeType": "Public",
		"profileImage": "https://www.clayton.edu/news/images/fall-reopening-2021.jpg",
		"collegeURL": "http://www.clayton.edu/",
		"locationCity": "Morrow",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "54%",
		"tuitionInState": "11,110",
		"tuitionOutOfState": "21,832",
		"exclude": "false"
	},
	{ 
		"collegeID": "5",
		"collegeName": "Columbus State University",
		"collegeType": "Public",
		"profileImage": "https://theatre.columbusstate.edu/images/riverside-theatre-complex-river.jpg",
		"collegeURL": "http://www.columbusstate.edu/",
		"locationCity": "Columbus",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "56%",
		"tuitionInState": "12,188",
		"tuitionOutOfState": "23,242",
		"exclude": "false"
	},
	{ 
		"collegeID": "6",
		"collegeName": "Kennesaw State University",
		"collegeType": "Public",
		"profileImage": "https://admissions.kennesaw.edu/images/Event_020720_LogoReveal_JG27.JPG",
		"collegeURL": "http://www.kennesaw.edu/",
		"locationCity": "Kennesaw",
		"locationState": "GA",
		"baselineACT": "24",
		"baselineGPA": "3.33",
		"baselineAPCount": "0",
		"acceptanceRate": "58%",
		"tuitionInState": "$15,786",
		"tuitionOutOfState": "$29,769",
		"exclude": "false"
	},
	{ 
		"collegeID": "7",
		"collegeName": "University of West Georgia",
		"collegeType": "Public",
		"profileImage": "https://www.westga.edu/assets/business/pics/roy-richards-sr-ext-3-wide.jpg",
		"collegeURL": "https://www.westga.edu/",
		"locationCity": "Carrollton",
		"locationState": "GA",
		"baselineACT": "20",
		"baselineGPA": "3.18",
		"baselineAPCount": "0",
		"acceptanceRate": "59%",
		"tuitionInState": "$16,776",
		"tuitionOutOfState": "$44,451",
		"exclude": "false"
	},
	{ 
		"collegeID": "8",
		"collegeName": "Fort Valley State University",
		"collegeType": "Public",
		"profileImage": "https://www.honorsociety.org/sites/default/files/uni-campus-18267",
		"collegeURL": "http://www.fvsu.edu/",
		"locationCity": "Fort Valley",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "61%",
		"tuitionInState": "$12,272",
		"tuitionOutOfState": "$22,994",
		"exclude": "false"
	},
	{ 
		"collegeID": "9",
		"collegeName": "Valdosta State University",
		"collegeType": "Public",
		"profileImage": "https://www.valdosta.edu/_images/west-hall-front-page-slider.jpg",
		"collegeURL": "https://www.valdosta.edu/",
		"locationCity": "Valdosta",
		"locationState": "GA",
		"baselineACT": "21",
		"baselineGPA": "3.21",
		"baselineAPCount": "0",
		"acceptanceRate": "63%",
		"tuitionInState": "$13,312",
		"tuitionOutOfState": "$26,530",
		"exclude": "false"
	},
	{ 
		"collegeID": "10",
		"collegeName": "Georgia State University",
		"collegeType": "Public",
		"profileImage": "https://cas.gsu.edu/files/2019/07/CAS-HOME-page-banner.jpg",
		"collegeURL": "http://www.gsu.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "24",
		"baselineGPA": "3.46",
		"baselineAPCount": "0",
		"acceptanceRate": "71%",
		"tuitionInState": "11,222",
		"tuitionOutOfState": "26,081",
		"exclude": "false"
	},
	{ 
		"collegeID": "11",
		"collegeName": "Emory University",
		"collegeType": "Private",
		"profileImage": "https://apply.emory.edu/_includes/images/sections/discover/about/0101401-15BM-F313_890x593.jpg",
		"collegeURL": "http://www.emory.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "32",
		"baselineGPA": "3.76",
		"baselineAPCount": "8",
		"acceptanceRate": "19%",
		"tuitionInState": "$72,604",
		"tuitionOutOfState": "$72,604",
		"exclude": "false"
	},
	{ 
		"collegeID": "12",
		"collegeName": "Oglethorpe University",
		"collegeType": "Private",
		"profileImage": "https://oglethorpe.edu/wp-content/themes/ogle_main/images/frontpage-hero-3_desktop.jpg",
		"collegeURL": "http://www.oglethorpe.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "6",
		"acceptanceRate": "67%",
		"tuitionInState": "$56,930",
		"tuitionOutOfState": "$56,930",
		"exclude": "false"
	},
	{ 
		"collegeID": "13",
		"collegeName": "Mercer University",
		"collegeType": "Private",
		"profileImage": "https://uc.mercer.edu/www/mu-uc/images/ucbillboard02.jpg",
		"collegeURL": "http://www.mercer.edu/",
		"locationCity": "Macon",
		"locationState": "GA",
		"baselineACT": "28",
		"baselineGPA": "3.80",
		"baselineAPCount": "6",
		"acceptanceRate": "78%",
		"tuitionInState": "$52,556",
		"tuitionOutOfState": "$52,556",
		"exclude": "false"
	},
	{ 
		"collegeID": "14",
		"collegeName": "Spelman College",
		"collegeType": "Private",
		"profileImage": "https://pbs.twimg.com/media/DyCh9RrWoAAon6T?format=jpg&name=large",
		"collegeURL": "http://www.spelman.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "24",
		"baselineGPA": "3.67",
		"baselineAPCount": "6",
		"acceptanceRate": "53%",
		"tuitionInState": "$46,325",
		"tuitionOutOfState": "$46,325",
		"exclude": "false"
	},
	{ 
		"collegeID": "15",
		"collegeName": "Morehouse College",
		"collegeType": "Private",
		"profileImage": "https://morehouse.edu/media/raftermen/student-life/Morehouse_Lifestyle_CCCC2831-1224x816.jpg",
		"collegeURL": "http://www.morehouse.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "21",
		"baselineGPA": "3.23",
		"baselineAPCount": "6",
		"acceptanceRate": "77%",
		"tuitionInState": "$52,580",
		"tuitionOutOfState": "$52,580",
		"exclude": "false"
	},
	{ 
		"collegeID": "16",
		"collegeName": "Agnes Scott College",
		"collegeType": "Private",
		"profileImage": "https://www.agnesscott.edu/assets/images/about/campus-main-hall-900x600.jpg",
		"collegeURL": "http://www.agnesscott.edu/",
		"locationCity": "Decatur",
		"locationState": "GA",
		"baselineACT": "26",
		"baselineGPA": "3.78",
		"baselineAPCount": "6",
		"acceptanceRate": "68%",
		"tuitionInState": "$56,705",
		"tuitionOutOfState": "$56,705",
		"exclude": "false"
	},
	{ 
		"collegeID": "17",
		"collegeName": "Berry College",
		"collegeType": "Private",
		"profileImage": "https://www.berry.edu/articles/G3582-Ford-Complex-23-bs62-crop-1.jpeg",
		"collegeURL": "http://www.berry.edu/",
		"locationCity": "Mount Berry",
		"locationState": "GA",
		"baselineACT": "27",
		"baselineGPA": "3.77",
		"baselineAPCount": "6",
		"acceptanceRate": "77%",
		"tuitionInState": "$50,316",
		"tuitionOutOfState": "$50,316",
		"exclude": "false"
	},
	{ 
		"collegeID": "18",
		"collegeName": "Savannah College of Art and Design",
		"collegeType": "Private",
		"profileImage": "https://www.scad.edu/sites/default/files/styles/swarm16x9_1170/public/Facilities/Savannah/Number-Nine/Number-Nine-exterior-Fall-2019-AS-2.jpg",
		"collegeURL": "http://www.scad.edu/",
		"locationCity": "Savannah",
		"locationState": "GA",
		"baselineACT": "24",
		"baselineGPA": "3.59",
		"baselineAPCount": "6",
		"acceptanceRate": "78%",
		"tuitionInState": "$49,433",
		"tuitionOutOfState": "$49,433",
		"exclude": "false"
	},
	{ 
		"collegeID": "19",
		"collegeName": "Toccoa Falls College",
		"collegeType": "Private",
		"profileImage": "https://tfc.edu/wp-content/uploads/2019/10/Entry-Sign.jpg",
		"collegeURL": "http://tfc.edu/",
		"locationCity": "Toccoa Falls",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "4",
		"acceptanceRate": "58%",
		"tuitionInState": "$38,104",
		"tuitionOutOfState": "$38,104",
		"exclude": "false"
	},
	{ 
		"collegeID": "20",
		"collegeName": "Brenau University",
		"collegeType": "Private",
		"profileImage": "https://7s60ez0ns6la1lf11py42789-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/072618-Pearce-AJR006-web.jpg",
		"collegeURL": "https://www.brenau.edu/",
		"locationCity": "Gainesville",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "4",
		"acceptanceRate": "92%",
		"tuitionInState": "$47,634",
		"tuitionOutOfState": "$47,634",
		"exclude": "false"
	}
]`;