var colleges = `[
	{ 
		"collegeID": "2",
		"collegeName": "Savannah State University",
		"collegeType": "Public",
		"profileImage": "https://www.savannahstate.edu/places/images/hill-hall.jpg",
		"collegeURL": "http://www.savannahstate.edu/",
		"locationCity": "Savannah",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "29%",
		"tuitionInState": "$9,493",
		"tuitionOutOfState": "$19,954",
		"exclude": "false"
	},
	{ 
		"collegeID": "3",
		"collegeName": "University of Georgia",
		"collegeType": "Public",
		"profileImage": "https://www.engineering.uga.edu/uploads/main/engr_coverdell.jpg",
		"collegeURL": "http://www.uga.edu/",
		"locationCity": "Athens",
		"locationState": "GA",
		"baselineACT": "30",
		"baselineGPA": "3.86",
		"baselineAPCount": "8",
		"acceptanceRate": "49%",
		"tuitionInState": "$17,412",
		"tuitionOutOfState": "$37,098",
		"exclude": "false"
	},
	{ 
		"collegeID": "11",
		"collegeName": "Georgia Institute of Technology",
		"collegeType": "Public",
		"profileImage": "https://www.gatech.edu/sites/default/files/uploads/images/superblock_images/tower.png",
		"collegeURL": "http://www.gatech.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "32",
		"baselineGPA": "3.86",
		"baselineAPCount": "8",
		"acceptanceRate": "22%",
		"tuitionInState": "$17,340",
		"tuitionOutOfState": "$38,452",
		"exclude": "false"
	},
	{ 
		"collegeID": "4",
		"collegeName": "Clayton State University",
		"collegeType": "Public",
		"profileImage": "https://www.clayton.edu/news/images/fall-reopening-2021.jpg",
		"collegeURL": "http://www.clayton.edu/",
		"locationCity": "Morrow",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "54%",
		"tuitionInState": "11,110",
		"tuitionOutOfState": "21,832",
		"exclude": "false"
	},
	{ 
		"collegeID": "5",
		"collegeName": "Columbus State University",
		"collegeType": "Public",
		"profileImage": "https://theatre.columbusstate.edu/images/riverside-theatre-complex-river.jpg",
		"collegeURL": "http://www.columbusstate.edu/",
		"locationCity": "Columbus",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "56%",
		"tuitionInState": "12,188",
		"tuitionOutOfState": "23,242",
		"exclude": "false"
	},
	{ 
		"collegeID": "6",
		"collegeName": "Kennesaw State University",
		"collegeType": "Public",
		"profileImage": "https://admissions.kennesaw.edu/images/Event_020720_LogoReveal_JG27.JPG",
		"collegeURL": "http://www.kennesaw.edu/",
		"locationCity": "Kennesaw",
		"locationState": "GA",
		"baselineACT": "24",
		"baselineGPA": "3.33",
		"baselineAPCount": "0",
		"acceptanceRate": "58%",
		"tuitionInState": "$15,786",
		"tuitionOutOfState": "$29,769",
		"exclude": "false"
	},
	{ 
		"collegeID": "7",
		"collegeName": "University of West Georgia",
		"collegeType": "Public",
		"profileImage": "https://www.westga.edu/assets/business/pics/roy-richards-sr-ext-3-wide.jpg",
		"collegeURL": "https://www.westga.edu/",
		"locationCity": "Carrollton",
		"locationState": "GA",
		"baselineACT": "20",
		"baselineGPA": "3.18",
		"baselineAPCount": "0",
		"acceptanceRate": "59%",
		"tuitionInState": "$16,776",
		"tuitionOutOfState": "$44,451",
		"exclude": "false"
	},
	{ 
		"collegeID": "8",
		"collegeName": "Fort Valley State University",
		"collegeType": "Public",
		"profileImage": "https://www.honorsociety.org/sites/default/files/uni-campus-18267",
		"collegeURL": "http://www.fvsu.edu/",
		"locationCity": "Fort Valley",
		"locationState": "GA",
		"baselineACT": "n/a",
		"baselineGPA": "n/a",
		"baselineAPCount": "0",
		"acceptanceRate": "61%",
		"tuitionInState": "$12,272",
		"tuitionOutOfState": "$22,994",
		"exclude": "false"
	},
	{ 
		"collegeID": "9",
		"collegeName": "Valdosta State University",
		"collegeType": "Public",
		"profileImage": "https://www.valdosta.edu/_images/west-hall-front-page-slider.jpg",
		"collegeURL": "https://www.valdosta.edu/",
		"locationCity": "Valdosta",
		"locationState": "GA",
		"baselineACT": "21",
		"baselineGPA": "3.21",
		"baselineAPCount": "0",
		"acceptanceRate": "63%",
		"tuitionInState": "$13,312",
		"tuitionOutOfState": "$26,530",
		"exclude": "false"
	},
	{ 
		"collegeID": "10",
		"collegeName": "Georgia State University",
		"collegeType": "Public",
		"profileImage": "https://cas.gsu.edu/files/2019/07/CAS-HOME-page-banner.jpg",
		"collegeURL": "http://www.gsu.edu/",
		"locationCity": "Atlanta",
		"locationState": "GA",
		"baselineACT": "24",
		"baselineGPA": "3.46",
		"baselineAPCount": "0",
		"acceptanceRate": "71%",
		"tuitionInState": "11,222",
		"tuitionOutOfState": "26,081",
		"exclude": "false"
	}
]`;